formatter: "markdown table"

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: .

sections:
  hide: []
  show: []

content: |-
  # Terraform Module

  {{ .Header }}

  ## Usage

  ```hcl
  module "example" {
    source = "git::https://github.com/Unilever-IaC-Core/<module-name>.git?ref=v1.0.0"

    # Add your configuration here
  }
  ```

  ## Usage

  This module deploys an Azure VM with networking components.

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
